version: "3.8"

services:
  jenifer-alvarez:
    image: jenifer-alvarez:latest
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jenifer-alvarez.entrypoints=http"
        - "traefik.http.routers.jenifer-alvarez.rule=Host(`jenifer-alvarez.byronrm.com`)"
        - "traefik.http.middlewares.jenifer-alvarez-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.jenifer-alvarez.middlewares=jenifer-alvarez-https-redirect"
        - "traefik.http.routers.jenifer-alvarez-secure.entrypoints=https"
        - "traefik.http.routers.jenifer-alvarez-secure.rule=Host(`jenifer-alvarez.byronrm.com`)"
        - "traefik.http.routers.jenifer-alvarez-secure.tls=true"
        - "traefik.http.routers.jenifer-alvarez-secure.tls.certresolver=http"
        - "traefik.http.routers.jenifer-alvarez-secure.service=jenifer-alvarez"
        - "traefik.http.services.jenifer-alvarez.loadbalancer.server.port=3000"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true